name: PR Validation

on: 
  push:
    branches:
      - main

jobs:

  # Formatter Github action for auto Dart formatting
  formatter: 
    uses: ./.github/workflows/formatter.yml
    
  build:

    needs: formatter

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.0.2

      - name: Verify Code Formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze

      - name: Testing
        run: flutter test

      

      
